### ISSUE TITLE
ghc-lib-9.2.3.20220527 doesn't build on GHC 8.10 when -haddock is enabled

### ISSUE THREAD

**Issue by kokobd** [digital-asset/ghc-lib#391]
Seems related to #344.
```
[103 of 357] Compiling GHC.CmmToAsm.AArch64.CodeGen ( compiler/GHC/CmmToAsm/AArch64/CodeGen.hs, dist/build/GHC/CmmToAsm/AArch64/CodeGen.o, dist/build/GHC/CmmToAsm/AArch64/CodeGen.dyn_o )

compiler/GHC/CmmToAsm/AArch64/CodeGen.hs:176:15: error:
    parse error on input ‘{- | debugIsOn -}’
    |
176 | ann doc instr {- | debugIsOn -} = ANN doc instr
    |               ^^^^^^^^^^^^^^^^^
cabal: Failed to build ghc-lib-9.2.3.20220527 (which is required by test:tests
from hls-hlint-plugin-1.0.4.0). See the build log above for details.
```

**Comment by shayne-fletcher** [comment]
@kokobd  the error message above indicates the error emanates from `ghc-lib`. why is `hs-lint-plugin` trying to link `ghc-lib`? hlint only requires `ghc-lib-parser`.

**Comment by shayne-fletcher** [comment]
reopened https://gitlab.haskell.org/ghc/ghc/-/issues/20920 and added a note

**Comment by kokobd** [comment]
@shayne-fletcher
> why does `hs-lint-plugin` have a build dependence on `ghc-lib`

Actually, the dependency is not necessary.
`hls-hlint-plugin` only uses some `SrcSpan` related functions, which can be imported from `ghc-lib-parser` instead.
![image](https://user-images.githubusercontent.com/16440269/177072958-929cce1c-aa24-4fe6-a340-e10133b275af.png)

I will fix that in HLS.

**Comment by shayne-fletcher** [comment]
> @shayne-fletcher
> > why does `hs-lint-plugin` have a build dependence on `ghc-lib`
> 
> Actually, the dependency is not necessary.
> `hls-hlint-plugin` only uses some `SrcSpan` related functions, which can be imported from `ghc-lib-parser` instead.
> ![image](https://user-images.githubusercontent.com/16440269/177072958-929cce1c-aa24-4fe6-a340-e10133b275af.png)
> 
> I will fix that in HLS.

awesome. that's the right thing to do for sure.
