### ISSUE TITLE
Need a GHC 9.2.1 release

### ISSUE THREAD

**Issue by LeventErkok** [digital-asset/ghc-lib#328]
Trying to build with GHC 9.2.1 (with `--allow-newer` to overcome base == 4.16 requirement) unsurprisingly fails with:

```
libraries/ghc-heap/GHC/Exts/Heap.hs:71:32: error:
    Not in scope: data constructor ‘LiftedRep’
   |
71 | instance HasHeapRep (a :: TYPE 'LiftedRep) where
   |                                ^^^^^^^^^^

libraries/ghc-heap/GHC/Exts/Heap.hs:74:32: error:
    Not in scope: data constructor ‘UnliftedRep’
    Perhaps you meant ‘Unlifted’ (imported from GHC.Exts)
   |
74 | instance HasHeapRep (a :: TYPE 'UnliftedRep) where
   |                                ^^^^^^^^^^^^
```

Admittedly this breakage is totally expected. Would be nice to have a 9.2.1 release.

**Comment by amesgen** [comment]
[ghc-lib-parser-9.2.1.20211030](https://hackage.haskell.org/package/ghc-lib-parser-9.2.1.20211030) just got uploaded to Hackage, but it does not compile on GHC 9.2.1 due to unnecessarily restrictive bounds on ghc-prim and bytestring. AFAICT, all restrictive upper bounds can be relaxed (using `--allow-newer='ghc-lib-parser:*'` works fine locally):

```
bytestring >=0.9 && <0.11 (latest: 0.11.1.0)
ghc-prim >0.2 && <0.8 (latest: 0.8.0)
time >=1.4 && <1.10 (latest: 1.13)
transformers >=0.5 && <0.6 (latest: 0.6.0.2)
```

**Comment by LeventErkok** [comment]
Thanks for the quick update! I'll leave this ticket open so you can close when you deem appropriate.

**Comment by shayne-fletcher** [comment]
i've adjusted the bounds on hackage. do you mind giving this another go after a `cabal update` please? i think it should be ok without `--allow-newer='ghc-lib-parser:*'` now. thanks for the heads up.

**Comment by amesgen** [comment]
Yes, compiling with GHC 9.2 now works fine without any special flags, thanks for the quick revision! This ticket can be closed then I think.

**Comment by LeventErkok** [comment]
Great. I'll close it then. Thanks for the very speedy patch.

**Comment by LeventErkok** [comment]
@shayne-fletcher Looks like `ghc-lib-parser-ex` has issues too. Filed: https://github.com/shayne-fletcher/ghc-lib-parser-ex/issues/99
