### ISSUE TITLE
ghc-lib-parser-8.10.1.20200523 does not build on GHC 8.4.4

### ISSUE THREAD

**Issue by tomjaguarpaw** [digital-asset/ghc-lib#226]
ghc-lib-parser-8.10.1.20200523 does not build on GHC 8.4.4 (but 8.6.5 is fine).  Perhaps the `base` dependency should be increased to exclude 8.4?

```
% ghc --version; ~/.ghcup/bin/cabal --version; ~/.ghcup/bin/cabal v2-install ghc-lib-parser-8.10.1.20200523
The Glorious Glasgow Haskell Compilation System, version 8.4.4
cabal-install version 3.2.0.0
compiled using version 3.2.0.0 of the Cabal library
Warning: The package list for 'hackage.haskell.org' is 47 days old.
Run 'cabal update' to get the latest list of available packages.
Warning: The package list for 'hackage.haskell.org' is 47 days old.
Run 'cabal update' to get the latest list of available packages.
Resolving dependencies...
Build profile: -w ghc-8.4.4 -O1
In order, the following will be built (use -v for more details):
 - ghc-lib-parser-8.10.1.20200523 (lib) (requires build)
Starting     ghc-lib-parser-8.10.1.20200523 (lib)
Building     ghc-lib-parser-8.10.1.20200523 (lib)

Failed to build ghc-lib-parser-8.10.1.20200523.
Build log (
/home/tom/.cabal/logs/ghc-8.4.4/ghc-lib-parser-8.10.1.20200523-97e28ebc83e3d1e1f5683d9ec22bede9abf014ce9734ff768c00e99d57f4bc16.log
):
Configuring library for ghc-lib-parser-8.10.1.20200523..
Preprocessing library for ghc-lib-parser-8.10.1.20200523..
In file included from /usr/include/stdio.h:33,
                 from /usr/lib/ghc/include/rts/Flags.h:16,
                 from /usr/lib/ghc/include/Rts.h:191,
                 from InfoTable.hsc:8:
InfoTable.hsc: In function ‘main’:
/usr/lib/ghc/template-hsc.h:75:24: error: ‘struct StgInfoTable_’ has no member named ‘srt’
                 (long) offsetof (t, f));
                        ^~~~~~~~
InfoTable.hsc:41:5: note: in expansion of macro ‘hsc_peek’
/usr/lib/ghc/template-hsc.h:79:24: error: ‘StgInfoTable’ {aka ‘struct StgInfoTable_’} has no member named ‘srt’
                 (long) offsetof (t, f));
                        ^~~~~~~~
InfoTable.hsc:59:5: note: in expansion of macro ‘hsc_poke’
compiling dist/build/GHC/Exts/Heap/InfoTable_hsc_make.c failed (exit code 1)
command was: /usr/bin/i686-linux-gnu-gcc -c dist/build/GHC/Exts/Heap/InfoTable_hsc_make.c -o dist/build/GHC/Exts/Heap/InfoTable_hsc_make.o -fno-stack-protector -fno-stack-protector -fuse-ld=gold -D__GLASGOW_HASKELL__=804 -Dlinux_BUILD_OS=1 -Di386_BUILD_ARCH=1 -Dlinux_HOST_OS=1 -Di386_HOST_ARCH=1 -Iincludes -Ighc-lib/stage0/lib -Ighc-lib/stage0/compiler/build -Icompiler -Idist/build/includes -Idist/build/ghc-lib/stage0/lib -Idist/build/ghc-lib/stage0/compiler/build -Idist/build/compiler -DTHREADED_RTS -DTHREADED_RTS -DGHC_IN_GHCI -Idist/build/autogen -Idist/build/global-autogen -include dist/build/autogen/cabal_macros.h -I/usr/lib/ghc/process-1.6.3.0/include -I/usr/lib/ghc/unix-2.7.2.2/include -I/usr/lib/ghc/time-1.8.0.2/include -I/usr/lib/ghc/bytestring-0.10.8.2/include -I/usr/lib/ghc/base-4.11.1.0/include -I/usr/lib/ghc/integer-gmp-1.0.2.0/include -I/usr/lib/ghc/include -I/usr/lib/ghc/include/
cabal: Failed to build ghc-lib-parser-8.10.1.20200523. See the build log above
for details.
```

**Comment by shayne-fletcher** [comment]
Unfortunately, this is indeed the case. This is a GHC restriction in that the minimum GHC required to bootstrap 8.10 is 8.6.     
```
    #  - Minimum GHC needed to bootstrap:
    #      +--------------+------------+
    #      | GHC flavor   |  version   |
    #      +==============+============+
    #      | ghc-8.8.*    |  >= 8.4.4  |
    #      | ghc-8.10.*   |  >= 8.6.5  | (since 09/29/2019, https://gitlab.haskell.org/ghc/ghc/commit/24620182abdfcc65a0cfc0e2f3bc391d464d0ad5)
    #      | ghc-8.11.*   |  >= 8.8.1  | (since 2020/03/31, https://gitlab.haskell.org/ghc/ghc/-/commit/57b888c0e90be7189285a6b078c30b26d092380)
    #      +--------------+------------+
```

**Comment by tomjaguarpaw** [comment]
Is there any chance you could adjust the build dependencies so cabal doesn't try to build it on a version of GHC that is not supported?

https://github.com/digital-asset/ghc-lib/blob/5ac40d8611b9a54c4740874a0944e9c78f1b424f/ghc-lib-gen/src/Ghclibgen.hs#L570

(`tested-with` is less important, but as it is it is currently incorrect)

https://github.com/digital-asset/ghc-lib/blob/5ac40d8611b9a54c4740874a0944e9c78f1b424f/ghc-lib-gen/src/Ghclibgen.hs#L710

**Comment by cocreature** [comment]
I’ve bumped the lower bound on base to 4.12 for all 8.10 releases of `ghc-lib` and `ghc-lib-parser`.
