### ISSUE TITLE
ghc-lib-parser-9.8.2.20240223 failed to build with ghc-9.8.3

### ISSUE THREAD

**Issue by juhp** [digital-asset/ghc-lib#563]
For Stackage Nightly with ghc-9.8.3:

```
       Building library for ghc-lib-parser-9.8.2.20240223..                                                                         
       [155 of 433] Compiling GHC.Unit.Types                                                                                        
                                                                                                                                    
       /home/curators/work/unpack-dir/unpacked/ghc-lib-parser-9.8.2.20240223-2c6194cfab3c6d198ba355d48ffc919705e56dc74190a757398fed9
667763406/compiler/GHC/Unit/Types.hs:127:25: error: [GHC-87543]                                                                     
           Ambiguous occurrence ‘Unit’.                                                                                             
           It could refer to                                                                                                        
              either ‘Control.DeepSeq.Unit’,                                                                                        
                     imported from ‘Control.DeepSeq’ at compiler/GHC/Unit/Types.hs:104:1-22,                                        
                  or ‘GHC.Unit.Types.Unit’,                                                                                         
                     defined at compiler/GHC/Unit/Types.hs:289:1.                                                                   
           |                                                                                                                        
       127 | type Module = GenModule Unit                                                                                           
           |                         ^^^^                                                                                           
                                                                                                                                    
       /home/curators/work/unpack-dir/unpacked/ghc-lib-parser-9.8.2.20240223-2c6194cfab3c6d198ba355d48ffc919705e56dc74190a757398fed9
667763406/compiler/GHC/Unit/Types.hs:334:14: error: [GHC-87543]                                                                     
           Ambiguous occurrence ‘Unit’.                                                                                             
           It could refer to                                                                                                        
              either ‘Control.DeepSeq.Unit’,                                                                                        
                     imported from ‘Control.DeepSeq’ at compiler/GHC/Unit/Types.hs:104:1-22,                                        
                  or ‘GHC.Unit.Types.Unit’,                                                                                         
                     defined at compiler/GHC/Unit/Types.hs:289:1.
           |
       334 | instance Ord Unit where
           |              ^^^^
        
       /home/curators/work/unpack-dir/unpacked/ghc-lib-parser-9.8.2.20240223-2c6194cfab3c6d198ba355d48ffc919705e56dc74190a757398fed9
667763406/compiler/GHC/Unit/Types.hs:337:15: error: [GHC-87543]
           Ambiguous occurrence ‘Unit’.
           It could refer to
              either ‘Control.DeepSeq.Unit’,
                     imported from ‘Control.DeepSeq’ at compiler/GHC/Unit/Types.hs:104:1-22,
                  or ‘GHC.Unit.Types.Unit’,
                     defined at compiler/GHC/Unit/Types.hs:289:1.
           |
       337 | instance Data Unit where
           |               ^^^^
:
:
:
```
many more Unit errors.

**Comment by shayne-fletcher** [comment]
ghc-lib-parser flavor 9.8.2 can't be built with a ghc 9.8.3 build compiler. when #561 lands it will correctly fail to produce a build plan for this case.

**Comment by juhp** [comment]
Thanks and I see you already released for 9.8.3 :pray: 

Only problem is it requires happy < 2 and we already have happy-2.0 in Stackage Nightly for quite a while now.

**Comment by juhp** [comment]
Actually 9.8.2 seemed to build fine with happy-2.0 - is the bound now necessary?

**Comment by shayne-fletcher** [comment]
i'll have a look

**Comment by shayne-fletcher** [comment]
i tested against happy 2.0.2. worked fine so i've removed the bound on [9.8.3.20241022](https://hackage.haskell.org/package/ghc-lib-parser-9.8.3.20241022)

**Comment by shayne-fletcher** [comment]
that's confusing. i already did this yesterday! anyway, i've done it again.

<img width="1061" alt="Screenshot 2024-10-23 at 8 08 55 AM" src="https://github.com/user-attachments/assets/1e2d3590-0b12-4e47-ad77-a55409161a44">

**Comment by shayne-fletcher** [comment]
checking post this revision update: `cabal update&&cabal get ghc-lib-parser-9.8.3.20241022 && cat ghc-lib-parser-9.8.3.20241022/ghc-lib-parser.cabal| grep happy` prints `build-tool-depends: alex:alex >= 3.1, happy:happy == 1.20.* || >= 2.0.2 && < 2.1` as expected. this was the case yesterday too so i am thoroughly at a loss to explain why hackage apparently "forgot" the revisions i made!

**Comment by shayne-fletcher** [comment]
if this doesn't stick i'll have to publish a new release with the new bounds.

**Comment by juhp** [comment]
Thanks again, nice: should be in the next Stackage Nightly too

**Comment by brandonchinn178** [comment]
@shayne-fletcher I'm also seeing this error with ghc-lib-parser-9.10.1.20240511 on GHC 9.8.3, with both happy 2.0.2 and 1.20.1.1.

https://github.com/fourmolu/fourmolu/actions/runs/11653342958/job/32445610879
https://github.com/fourmolu/fourmolu/actions/runs/11647229858/job/32432246122

I'm trying GHC 9.10 now, but not sure if you know of a solution with 9.8.3?

**Comment by shayne-fletcher** [comment]
> @shayne-fletcher I'm also seeing this error with ghc-lib-parser-9.10.1.20240511 on GHC 9.8.3, with both happy 2.0.2 and 1.20.1.1.
> 
> https://github.com/fourmolu/fourmolu/actions/runs/11653342958/job/32445610879 https://github.com/fourmolu/fourmolu/actions/runs/11647229858/job/32432246122
> 
> I'm trying GHC 9.10 now, but not sure if you know of a solution with 9.8.3?

this turns out to be genuine breakage due to incompatibility with 9.8.3.

i pushed a new release ghc-lib[-parser]-9.10.1.20241103. confirmed that it builds with 9.8.3 and happy 2.1.2.

**Comment by brandonchinn178** [comment]
Thanks, I'll try that. Also, I'm trying to build ghc-lib-parser with time 1.14, which is the version that comes with GHC 9.10. Any reason why `time` is pinned to `< 1.13`?

**Comment by shayne-fletcher** [comment]
> Thanks, I'll try that. Also, I'm trying to build ghc-lib-parser with time 1.14, which is the version that comes with GHC 9.10. Any reason why `time` is pinned to `< 1.13`?

no, it's just wrong. i've tested with 1.14 and bumped the bounds on hackage for the 9.10 packages to < 1.15.
