### ISSUE TITLE
Is it expected that ghc-lib-parser-8.10.7.20210828 fails to build with GHC 9.0.2?

### ISSUE THREAD

**Issue by Bodigrim** [digital-asset/ghc-lib#349]
```
$ cabal unpack ghc-lib-parser-8.10.7.20210828
$ cd ghc-lib-parser-8.10.7.20210828
$ cabal build -w ghc-9.0.2
<skipped>
[ 65 of 228] Compiling Util

compiler/utils/Util.hs:43:28: error:
    Ambiguous occurrence ‘singleton’
    It could refer to
       either ‘Data.List.singleton’,
              imported from ‘Data.List’ at compiler/utils/Util.hs:141:1-38
              (and originally defined in ‘base-4.15.1.0:Data.OldList’)
           or ‘Util.singleton’, defined at compiler/utils/Util.hs:558:1
   |
43 |         isSingleton, only, singleton,
   |                            ^^^^^^^^^
```

**Comment by shayne-fletcher** [comment]
hi @Bodigrim ! i'm sorry to advise that yes, it is expected.

being `ghc` source, `ghc-lib-parser` operates under the same constraints as `ghc` itself in that newer versions of `ghc` in general can't be expected to build older versions. in this case, the range of versions suitable for `ghc-lib-parser-8.10.7.*` are *[ghc-8.6.5, ghc-9.0.1)*.

in fact in https://github.com/digital-asset/ghc-lib/pull/336  bounds on base were tightened in such a way that should have prevented obtaining a build plan. unfortunately that PR was landed in nov after the 8.10.7.20210828 release. in light of this, i'll push a new 8.10.7 version to hackage with those improved bounds today.

i'm sorry that you were inconvenienced by this!

**Comment by Bodigrim** [comment]
No problem, as a Hackage trustee I put two revisions:
https://hackage.haskell.org/package/ghc-lib-parser-8.10.5.20210606/revisions/
https://hackage.haskell.org/package/ghc-lib-parser-8.10.6.20210814/revisions/
